name: Update Greeting File

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Greeting File
        run: |
          echo "This message was added by GitHub Actions on $(date)." >> greeting.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add greeting.txt
          git commit -m "Update greeting.txt via GitHub Actions"
          git push g