name: Greeting Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: |
          echo "Reading the greeting message..."
          cat greeting.txt